APP_BG = "#F6FAFD"
CARD_BG = "#FFFFFF"
BORDER = "#D9E6F2"
PRIMARY = "#1E88E5"
DEEP_BLUE = "#0D47A1"
SOFT_BLUE = "#EAF4FF"
TEXT_MAIN = "#102A43"
TEXT_MUTED = "#627D98"

STATUS_READY = "#2E7D32"
STATUS_MISSING = "#F9A825"
STATUS_ERROR = "#C62828"
STATUS_RUNNING = "#1565C0"

FONT_FAMILY_HEADER = "Segoe UI"
FONT_FAMILY_BODY = "Segoe UI"

# Legacy Aliases to support config.py compilation
BACKGROUND = APP_BG
TEXT = TEXT_MAIN
MUTED = TEXT_MUTED
PRIMARY_DARK = DEEP_BLUE
PRIMARY_SOFT = SOFT_BLUE
SECONDARY = SOFT_BLUE
SECONDARY_HOVER = BORDER
SUCCESS = STATUS_READY
WARNING = STATUS_MISSING
DANGER = STATUS_ERROR
